### ISSUE TITLE
Math Driver Extend

### ISSUE THREAD

**Issue by KonstaMF** [Alxs009/Universal-Math-Fixer#1]
Hello, can this https://github.com/KonstaMF/Math-Driver-Extend implemented in the .NET mscorlib.dll library or as a universal Windows driver.

**Comment by Alxs009** [comment]
> Hello, can this https://github.com/KonstaMF/Math-Driver-Extend implemented in the .NET mscorlib.dll library or as a universal Windows driver.

My utility does not apply to this. It is designed to call Math methods to get the result and write down the instruction in IL.

If you want to extend Math, create your own class like Math.
